### PR TITLE
Support YouTube HLS to play live streams

### PR DESCRIPTION
**Pull request by waliid**
# Pull request

## Description

This PR allows us to play live content in HLS format.

Image 1
Image 2

## Changes made

- Added the `hlsManifestUrl` property to the `InnerTube` component.
- Exposed the `hlsManifestUrl` property through the YouTube class, allowing easy access to the HLS manifest URL.
- Introduced the `LiveStreamabilityRenderer` to handle live streaming capabilities in the application. This renderer is not a `Boolean` anymore.
- Updated the `README.md` file to reflect the latest improvements.

## Checklist

- [x] APIs have been properly documented (if relevant).
- [x] The documentation has been updated (if relevant).
- [x] New unit tests have been written (if relevant).

### CODE REVIEW

**Comment by waliid** [comment]
Could you please review my code @alexeichhorn?

**Comment by alexeichhorn** [comment]
Looks good. Thanks for contributing 😃 
Am I correct in assuming that this only works for livestreams? Or are there also videos with HLS?

**Comment by waliid** [comment]
> Looks good. Thanks for contributing 😃
> Am I correct in assuming that this only works for livestreams? Or are there also videos with HLS?

You're welcome. Yep! You are correct. It's only for livestreams and from what I know and what I've tested, the YouTube `onDemand` streams don't have an `hlsManifestUrl`.

**Comment by alexeichhorn** [comment]
Will merge it and change the structure a bit. I want it to be a bit more future-proof and conforms to a similar style that already exists for on-demand content

**Comment by waliid** [comment]
Alright ;) thank you!

**Pull request merged**
